### ISSUE TITLE
Question about Capabilities

### ISSUE THREAD

**Issue by hoilett** [vishishere123/Anand1#1]
Hi Vishal,
What do you want Bluetooth to do?

**Comment by vishishere123** [comment]
Hey Orlando

I would perhaps want the Bluetooth to be able to sync with an app in a cellphone, say a fitness app, where I can store the data related to my jog, run, sleep times etc.  Mostly like those fitness trackers like FitBit and others.

Regards
Vishal

**Comment by hoilett** [comment]
Sounds good. If you could write that in the document that would be helpful. Thanks.
